### ISSUE TITLE
`WebChimera.js` not compatible with latest `Electron`

### ISSUE THREAD

**Issue by MikeGCV** [RSATom/WebChimera.js#40]
Hello, i'm trying to build for electron  but it give's me this error

C:\WebChimera.js\src\JsVlcPlayer.cpp(396): error C2039: 'GetIndexedPropertiesExternalArrayData' : is not a member of
v8::Object' [C:\WebChimera.js\build\WebChimera.js.vcxproj]

Thank you

**Comment by jaruba** [comment]
check this cool thing out: https://github.com/Ivshti/wcjs-prebuilt

**Comment by MikeGCV** [comment]
Thanks, will try, is it build for 0.31 of electron?

**Comment by jaruba** [comment]
Let's find out! summoning @Ivshti

**Comment by Ivshti** [comment]
@MikeGCV no, the prebuilt has for 0.29 

currently we need to setup artifacts from Travis CI and AppVeyor to be able to build for most of the recent versions

Summoning @RSATom

**Comment by MikeGCV** [comment]
It looks like "GetIndexedPropertiesExternalArrayData" was removed from from V8 object in the latest iojs version

**Comment by Ivshti** [comment]
@MikeGCV yes, we talked about this with @RSATom a while back 

We have to use another API for external buffers, instead of this solution which is kind of a hack.

**Comment by RSATom** [comment]
it seems they finally did it... Will have to look to the new v8 api...

**Comment by RSATom** [comment]
Did anybody try `wcjs` with `Electron` v0.30 ?

**Comment by Ivshti** [comment]
@RSATom I did, it works fine with the 0.29 build

**Comment by RSATom** [comment]
yes, with 0.29, but how about v0.30? did you try it?

**Comment by Ivshti** [comment]
I expressed myself wrong - works fine in electron 0.30 with the wcjs build for 0.29

**Comment by MikeGCV** [comment]
Just builded successfully against 0.30.6, in windows ia32
From 0.29 to 0.30.6 they have used iojs 2.3.1
In 0.31 they changed  iojs to 3.1.0 (V8 changes) and chrome 44

**Comment by RSATom** [comment]
@MikeGCV, thanks for info, it's very useful.

**Comment by RSATom** [comment]
I can't understand. What electron version is latest?
https://github.com/atom/electron/releases
https://github.com/mafintosh/electron-prebuilt/releases

**Comment by MikeGCV** [comment]
From what i understand, they are maintaining two versions, 0.30.6 (in which webchimera.js compiles), and the new 0.31 (which changes to iojs 3.1.0 and chrome 44). This is the one were webchimera.js doesn't build. From what i've been looking, the GetIndexedPropertiesExternalArrayData was remove from iojs 3.0.0 up

**Comment by RSATom** [comment]
@MikeGCV, thanks
@Ivshti, what `Electron` version we should use?

**Comment by Ivshti** [comment]
Good job @RSATom  !

Bet on 0.30. 

In general Chromium 45 fixes many issues of chromium 44, but the simple fact they've decided to maintain 0.30 too shows 0.31 is not stable enough.

Personally I've chosen 0.29, they are some non-serious issues with 0.30 (like tray appearance on OS X).
But bet on 0.30, which is basically "newest safe" option.

Also what's compiled for 0.30 should be runnable on 0.29 and vice versa.

**Comment by RSATom** [comment]
Ok, thanks. Will downgrade to Electron `0.30.6`

**Comment by RSATom** [comment]
published updated version

**Comment by MikeGCV** [comment]
I understand the decision, but today they released 0.31.1, i don't know what they're doing

**Comment by Ivshti** [comment]
Exactly, fixing some issues that they found on 0.31. My advice is to wait until 0.31.4 (for example) or 0.32

**Comment by RSATom** [comment]
@MikeGCV, you still could use newer `Electron` version, just set required version as in https://github.com/RSATom/WebChimera.js/blob/master/build_electron.sh

**Comment by MikeGCV** [comment]
@RSATom  yes, i understand, but it won't build with 0.31.1, or the build is not needed?

**Comment by RSATom** [comment]
@MikeGCV, it should build fine. I've fixed compatibility issue at least with `Electron` v0.31

**Comment by RSATom** [comment]
@MikeGCV, I've tested `wcjs` with `Electron` v0.31.1 - it works fine.

**Comment by MikeGCV** [comment]
@RSATom Thank you very much, that's very good news, sorry, i should have tested

**Comment by MikeGCV** [comment]
Just builded for 0.31.2, worked flawlessly
